spring:
  config:
    activate:
      on-profile: dev
  application:
    name: ouch
  datasource:
    url: jdbc:mysql://52.78.221.55:3306/ouchdb_ver0?serverTimezone=Asia/Seoul
    username: test
    password: ouch
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jasypt:
  encryptor:
    password: jasyptKey
    bean: jasyptEncryptor

jwt:
  secret: ENC(IM7p+pHVt55x2ugo5fWNu03bDw76hiCwRRWk/Os7r3Cvpcbk1lKtLccdbaWmCI+bOTsjepwpIpbHSVorbDTd0t0JfKMuskq75YfF9ehPzjw/4nEkK5Pli/FnDqeiT6fiFSnVvlGrsswp3BVR0YOzwbxMTAz06cGEu+fNqW3DzLBpv3WGIzcMP4BodGohaoct)